{
 "title": "Flink",
 "time": { "from": "2022-02-27T13:05:26.037Z", "to": "2022-02-27T13:18:08.249Z" },
 "panels": [
  {
   "title": "Flink",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Records consumed - internal metrics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_numRecordsOutPerSecond{operator_name=\"Source:_ClickEvent_Source\"})"
      }
     ]
    },
    {
     "title": "Records produced - Internal metrics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_numRecordsOutPerSecond{})"
      }
     ]
    },
    {
     "title": "Throughput - In",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_flinkRecordsConsumed{task_name=\"Source:_ClickEvent_Source\"})"
      }
     ]
    },
    {
     "title": "Throughput - Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_flinkRecordsProduced{})"
      }
     ]
    },
    {
     "title": "End to end Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "e2eLatency{}" }
     ]
    },
    {
     "title": "Source-to-Sink latency - internal metrics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(flink_taskmanager_job_latency_source_id_source_subtask_index_operator_id_operator_subtask_index_latency{})"
      },
      {
       "expr": "min(flink_taskmanager_job_latency_source_id_source_subtask_index_operator_id_operator_subtask_index_latency{})"
      },
      {
       "expr": "avg(flink_taskmanager_job_latency_source_id_source_subtask_index_operator_id_operator_subtask_index_latency{})"
      }
     ]
    },
    {
     "title": "Number of restarts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "flink_jobmanager_job_numRestarts"
      }
     ]
    },
    {
     "title": "Wrong windows",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      { "expr": "falseResults{}" }
     ]
    }
   ]
  },
  {
   "title": "Flink checkpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Checkpoint ID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "flink_jobmanager_job_totalNumberOfCheckpoints{}"
      }
     ]
    },
    {
     "title": "Checkpoint Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointDuration{}"
      }
     ]
    },
    {
     "title": "Checkpoint size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointSize{}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "KafkaConsumer - Record consumed rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_KafkaConsumer_records_consumed_rate{}"
      }
     ]
    },
    {
     "title": "KafkaProducer - record sent rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_KafkaProducer_record_send_rate{}"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage -Task managers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "flink_taskmanager_System_CPU_Usage{}"
      }
     ]
    },
    {
     "title": "CPU Usage -Job Managers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "flink_jobmanager_System_CPU_Usage{}"
      }
     ]
    },
    {
     "title": "Queue length",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "max(flink_taskmanager_job_task_buffers_inputQueueLength{})"
      },
      {
       "expr": "max(flink_taskmanager_job_task_buffers_outputQueueLength{})"
      }
     ]
    }
   ]
  }
 ]
}