{
 "title": "Benchmarking",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Disk space remaining",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype=\"ext4\"}"
    }
   ]
  },
  {
   "title": "Node metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true
  },
  {
   "title": "CPU Load - KStreams Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "node_load1{instance=~\"node9:9100|node10:9100|node11:9100|node12:9100\"}"
    }
   ]
  },
  {
   "title": "Available Memory - KStreams Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"node9:9100|node10:9100|node11:9100|node12:9100\"}"
    }
   ]
  },
  {
   "title": "Disk read - KStreams Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(node_disk_read_bytes_total{instance=~\"node9:9100|node10:9100|node11:9100|node12:9100\"}[2s])"
    }
   ]
  },
  {
   "title": "Disk write - KStreams Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(node_disk_written_bytes_total{instance=~\"node9:9100|node10:9100|node11:9100|node12:9100\"}[2s])"
    }
   ]
  },
  {
   "title": "Network Bytes Out - KStreams Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"node9:9100|node10:9100|node11:9100|node12:9100\"}[2s])"
    }
   ]
  },
  {
   "title": "Network Bytes In - KStreams Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"node9:9100|node10:9100|node11:9100|node12:9100\"} [2s])"
    }
   ]
  },
  { "title": "Kafka Custom Probes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Kafka Brokers Throughput - In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "de_tum_in_msrg_kafka_stream_custom_metrics_customThroughput{}"
    }
   ]
  },
  { "title": "Utils", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Data generator throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "increase(de_tum_in_msrg_datagen_records_total[2s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "End to end Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "de_tum_in_msrg_latcal_latency" }
   ]
  }
 ]
}