{
 "title": "Storm dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Faults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ALERTS{alertname=~\"fault-injection\", alertstate=~\"firing\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Utils", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Data generator throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(de_tum_in_msrg_datagen_records_total[2s])"
    }
   ]
  },
  {
   "title": "Events generated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "de_tum_in_msrg_datagen_records_total"
    }
   ]
  },
  {
   "title": "End to end Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "de_tum_in_msrg_latcal_latency" }
   ]
  },
  {
   "title": "Throughput - Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(de_tum_in_msrg_pgv_processed_total)\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Windows with PB events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "de_tum_in_msrg_pgv_duplicate_window_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Windows with unprocessed events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(de_tum_in_msrg_pgv_unprocessed) - 6"
    }
   ]
  },
  {
   "title": "Duplicate events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "de_tum_in_msrg_pgv_duplicate_total"
    }
   ]
  },
  {
   "title": "Processed events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "de_tum_in_msrg_pgv_processed_total"
    }
   ]
  },
  {
   "title": "Expected number of windows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "de_tum_in_msrg_pgv_expected_windows"
    }
   ]
  },
  {
   "title": "Number of received windows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "de_tum_in_msrg_pgv_received_windows_total"
    }
   ]
  },
  {
   "title": "Correct outputs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "de_tum_in_msrg_pgv_correct_output_total",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Incorrect outputs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "de_tum_in_msrg_pgv_incorrect_output_total"
    }
   ]
  },
  {
   "title": "Incorrect outputs - Lower than expected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "de_tum_in_msrg_pgv_incorrect_lower_output_total"
    }
   ]
  },
  {
   "title": "Incorrect outputs - Higher than expected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "de_tum_in_msrg_pgv_incorrect_higher_output_total"
    }
   ]
  },
  {
   "title": "Output counter histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "de_tum_in_msrg_pgv_output_counter_bucket{le!=\"10.0\"}",
     "legendFormat": "{{key}}-{{le}}"
    }
   ]
  },
  { "title": "Flink", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Flink records consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_flinkRecordsConsumed{operator_name=\"Source:_ClickEvent_src\", instance=\"taskmanager1:9249\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_flinkRecordsConsumed{operator_name=\"Source:_ClickEvent_src\", instance=\"taskmanager2:9249\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_flinkRecordsConsumed{operator_name=\"Source:_ClickEvent_src\", instance=\"taskmanager3:9249\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Kafka Streams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Kafka Streams - Ingestion rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "de_tum_in_msrg_kafka_stream_custom_metrics_customThroughput",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "CPU Load - Storm Cluster",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "node_load1{instance=~\"node1:9100|node2:9100|node3:9100|node4:9100|node5:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Memory - Storm Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"node2:9100|node1:9100|node3:9100|node4:9100|node5:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk write - Storm Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(node_disk_written_bytes_total{instance=~\"node1:9100|node2:9100|node3:9100|node4:9100|node5:9100\"}[2s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk read - Storm Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(node_disk_read_bytes_total{device=\"vda\", instance=~\"node1:9100|node2:9100|node3:9100|node4:9100|node5:9100\"}[2s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Bytes In - Storm Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{instance=~\"node1:9100|node2:9100|node3:9100|node4:9100|node5:9100\", device=\"eth0\"}[2s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Bytes Out - Storm Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(node_network_transmit_bytes_total{instance=~\"node1:9100|node2:9100|node3:9100|node4:9100|node5:9100\", device=\"eth0\"}[2s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk space remaining - Storm cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=~\"node1:9100|node2:9100|node3:9100|node4:9100|node5:9100\", fstype=\"ext4\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}