{
 "title": "Storm dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Faults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ALERTS{alertname=~\"fault-injection\", alertstate=~\"firing\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Utils", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Data generator throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(de_tum_in_msrg_datagen_records_total[2s])"
    }
   ]
  },
  {
   "title": "End to end Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "de_tum_in_msrg_latcal_latency" }
   ]
  },
  {
   "title": "Events generated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "de_tum_in_msrg_datagen_records_total"
    }
   ]
  },
  {
   "title": "Processed events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "de_tum_in_msrg_pgv_processed_total"
    }
   ]
  },
  {
   "title": "Duplicate events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "de_tum_in_msrg_pgv_duplicate_total"
    }
   ]
  },
  {
   "title": "Windows with unprocessed events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    { "expr": "de_tum_in_msrg_pgv_unprocessed" }
   ]
  },
  {
   "title": "Correct outputs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "de_tum_in_msrg_pgv_correct_output_total"
    }
   ]
  },
  {
   "title": "Incorrect outputs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "de_tum_in_msrg_pgv_incorrect_output_total{}"
    }
   ]
  },
  {
   "title": "Incorrect outputs - Lower than expected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "de_tum_in_msrg_pgv_incorrect_lower_output_total"
    }
   ]
  },
  {
   "title": "Incorrect outputs - Higher than expected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "de_tum_in_msrg_pgv_incorrect_higher_output_total"
    }
   ]
  },
  {
   "title": "Expected number of windows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "de_tum_in_msrg_pgv_expected_windows"
    }
   ]
  },
  {
   "title": "Number of received windows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "de_tum_in_msrg_pgv_received_windows_total"
    }
   ]
  },
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "CPU Load - Storm Cluster",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "node_load1{instance=~\"node1:9100|node2:9100|node3:9100|node4:9100|node5:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Memory - Storm Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"node2:9100|node1:9100|node3:9100|node4:9100|node5:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk write - Storm Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(node_disk_written_bytes_total{instance=~\"node1:9100|node2:9100|node3:9100|node4:9100|node5:9100\"}[2s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk read - Storm Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(node_disk_read_bytes_total{device=\"vda\", instance=~\"node1:9100|node2:9100|node3:9100|node4:9100|node5:9100\"}[2s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Bytes In - Storm Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{instance=~\"node1:9100|node2:9100|node3:9100|node4:9100|node5:9100\", device=\"eth0\"}[2s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Bytes Out - Storm Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(node_network_transmit_bytes_total{instance=~\"node1:9100|node2:9100|node3:9100|node4:9100|node5:9100\", device=\"eth0\"}[2s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk space remaining - Storm cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=~\"node1:9100|node2:9100|node3:9100|node4:9100|node5:9100\", fstype=\"ext4\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}