version: '3.9'

services:


  kafka1:
    image: bitnami/kafka:3.6.0
    hostname: kafka1
    environment:
      KAFKA_CFG_NODE_ID: 1001
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: INSIDE://:9092,CONTROLLER://:9093,OUTSIDE://:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,CONTROLLER:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1001@kafka1:9093,1002@kafka2:9093,1003@kafka3:9093
      KAFKA_KRAFT_CLUSTER_ID: klCAuWnLSf2HkOCaR3FOWg
      KAFKA_CFG_ADVERTISED_LISTENERS: INSIDE://kafka1:9092,OUTSIDE://node1:9094
      KAFKA_CFG_METRICS_SAMPLE_WINDOW_MS: 1000
      KAFKA_CFG_LOG_MESSAGE_TIMESTAMP_TYPE: LogAppendTime
      KAFKA_CFG_LOG_RETENTION_BYTES: 2684354560 #2.5 GB
      KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS: 60000 # 1 minutes
      KAFKA_CFG_MIN_INSYNC_REPLICAS: 2
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_CFG_OFFSETS_TOPIC_NUM_PARTITIONS: 3
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_CFG_GROUP_MIN_SESSION_TIMEOUT_MS: 3000

    networks:
      infra:
    ports:
      - mode: host
        published: 9094
        target: 9094

    configs:
      - source: kafka_config
        target: /bitnami/kafka/config/log4j.properties

    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==kafka1"


  kafka2:
    image: bitnami/kafka:3.6.0
    hostname: kafka2
    environment:
      KAFKA_CFG_NODE_ID: 1002
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: INSIDE://:9092,CONTROLLER://:9093,OUTSIDE://:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,CONTROLLER:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1001@kafka1:9093,1002@kafka2:9093,1003@kafka3:9093
      KAFKA_KRAFT_CLUSTER_ID: klCAuWnLSf2HkOCaR3FOWg
      KAFKA_CFG_ADVERTISED_LISTENERS: INSIDE://kafka2:9092,OUTSIDE://node2:9094
      KAFKA_CFG_METRICS_SAMPLE_WINDOW_MS: 1000
      KAFKA_CFG_LOG_MESSAGE_TIMESTAMP_TYPE: LogAppendTime
      KAFKA_CFG_LOG_RETENTION_BYTES: 2684354560 #2.5 GB
      KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS: 60000 # 1 minutes
      KAFKA_CFG_MIN_INSYNC_REPLICAS: 2
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_CFG_OFFSETS_TOPIC_NUM_PARTITIONS: 3
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_CFG_GROUP_MIN_SESSION_TIMEOUT_MS: 3000
    networks:
      infra:
    ports:
      - mode: host
        published: 9094
        target: 9094

    configs:
      - source: kafka_config
        target: /bitnami/kafka/config/log4j.properties

    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==kafka2"
  #
  #
  kafka3:
    image: bitnami/kafka:3.6.0
    hostname: kafka3
    environment:
      KAFKA_CFG_NODE_ID: 1003
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: INSIDE://:9092,CONTROLLER://:9093,OUTSIDE://:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,CONTROLLER:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1001@kafka1:9093,1002@kafka2:9093,1003@kafka3:9093
      KAFKA_KRAFT_CLUSTER_ID: klCAuWnLSf2HkOCaR3FOWg
      KAFKA_CFG_ADVERTISED_LISTENERS: INSIDE://kafka3:9092,OUTSIDE://node3:9094
      KAFKA_CFG_METRICS_SAMPLE_WINDOW_MS: 1000
      KAFKA_CFG_LOG_MESSAGE_TIMESTAMP_TYPE: LogAppendTime
      KAFKA_CFG_LOG_RETENTION_BYTES: 2684354560 #2.5 GB
      KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS: 60000 # 1 minutes
      KAFKA_CFG_MIN_INSYNC_REPLICAS: 2
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_CFG_OFFSETS_TOPIC_NUM_PARTITIONS: 3
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_CFG_GROUP_MIN_SESSION_TIMEOUT_MS: 3000
    networks:
      infra:
    ports:
      - mode: host
        published: 9094
        target: 9094

    configs:
      - source: kafka_config
        target: /bitnami/kafka/config/log4j.properties

    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==kafka3"


configs:
  kafka_config:
    file: ./conf/log4j-kafka.properties

networks:
  infra:
    external: true
    name: infra
