---

#tasks:
#  - server:
#      address: "127.0.0.1"
#      port: 52923
#    containers:
#      - "kstreams_kstreams"
#    operation: "netem"
#    operationOptns:
#      - option: "--interface"
#        value: "docker_gwbridge"
#      - option: "--duration"
#        value: "10s"
#      - option: "--tc-image"
#        value: "gaiadocker/iproute2"
#
#    suboperation: "delay"
#    suboperationOptns:
#      - option: "--time"
#        value: "100"
#    startDelay: 10
#
#  - server:
#      address: "127.0.0.1"
#      port: 52923
#    containers:
#      - "utils_datagen"
#    operation: "kill"
#    operationOptns: []
#    suboperation: ""
#    suboperationOptns: []
#    startDelay: 120

  tasks:
  - server:
      address: "0.0.0.0"
      port: 52923
    containers:
      - "flink_taskmanager2"
    operation: "netem"
    operationOptns:
      #      - option: "--interface"
      #        value: "docker_gwbridge"
      - option: "--duration"
        value: "60s"
      - option: "--tc-image"
        value: "gaiadocker/iproute2"

    suboperation: "corrupt"
    suboperationOptns:
      - option: "--percent"
        value: "50"
    startDelay: 5