---
servers:
  - address: "localhost:52923"
    containers:
      - "some-nginx"
operation: "kill"
operationOptns: []
suboperation: ""
suboperationOptns: []


#---
#servers:
#  - address: "localhost:52923"
#    containers:
#      - "some-nginx"
#operation: "netem"
#operationOptns:
#  - option: "-d"
#    value: "10s"
#  - option: "--tc-image"
#    value: "gaiadocker/iproute2"
#suboperation: "delay"
#suboperationOptns:
#  - option: "-t"
#    value: "1000"
