---
server:
  address: "pumbasrvr"
  port: 52923
containers:
    - "infra_taskmanager"
operation: "kill"
operationOptns: []
suboperation: ""
suboperationOptns: []
# in seconds
startDelay: 30

#
#---
#server:
#  address: "taskmanager"
#  port: 52923
#containers:
#  - "infra_taskmanager"
#operation: "netem"
#operationOptns:
#  - option: "-d"
#    value: "10s"
#  - option: "--tc-image"
#    value: "gaiadocker/iproute2"
#suboperation: "delay"
#suboperationOptns:
#  - option: "-t"
#    value: "1000"
## in seconds
#startDelay: 10