---
#server:
#  address: "pumbasrvr_tm1"
#  port: 52923
#containers:
#    - "infra_taskmanager"
#operation: "kill"
#operationOptns: []
#suboperation: ""
#suboperationOptns: []
## in seconds
#startDelay: 90

#
#---
server:
  address: "pumbasrvr_tm1"
  port: 52923
containers:
  - "infra_taskmanager"
operation: "netem"
operationOptns:
  - option: "-d"
    value: "90s"
  - option: "-i"
    value: "infra_infra"
  - option: "--tc-image"
    value: "gaiadocker/iproute2"
suboperation: "delay"
suboperationOptns:
  - option: "-t"
    value: "2000"
# in seconds
startDelay: 90