---
servers:
  - address: "taskmanager:52923"
    containers:
      - "DSPF-BM_taskmanager"
operation: "kill"
operationOptns: []
suboperation: ""
suboperationOptns: []
# in seconds
startDelay: 30


#---
#servers:
#  - address: "localhost:52923"
#    containers:
#      - "some-nginx"
#operation: "netem"
#operationOptns:
#  - option: "-d"
#    value: "10s"
#  - option: "--tc-image"
#    value: "gaiadocker/iproute2"
#suboperation: "delay"
#suboperationOptns:
#  - option: "-t"
#    value: "1000"
