version: '3.9'

services:
  jobmanager:
    image: jawadtahir/flink-ops-playground:latest
#    image: flink:1.15.2-scala_2.12-java11
    networks:
      - infra
    entrypoint: "jobmanager.sh start-foreground"
    ports:
      - target: 8081
        published: 48081
        mode: host
    volumes:
#      - ./lib:/opt/flink/lib
#      - ./usrlib:/opt/flink/usrlib
#      - ./conf:/opt/flink/conf
#      - ./lib/oshi-core-4.4.2.jar:/opt/flink/lib/oshi-core-4.4.2.jar
#      - ./lib/jna-5.8.0.jar:/opt/flink/lib/jna-5.8.0.jar
#      - ./lib/jna-platform-5.8.0.jar:/opt/flink/lib/jna-platform-5.8.0.jar
      - /home/ubuntu/hadoop/hadoop-3.3.6:/hadoop
      - /usr/lib/jvm/java-11-openjdk-amd64:/usr/lib/jvm/java-11-openjdk-amd64

    configs:
      - source: flink_conf
        target: /opt/flink/conf/flink-conf.yaml

      - source: masters_conf
        target: /opt/flink/conf/masters

      - source: workers_conf
        target: /opt/flink/conf/workers

      - source: flink_console_log
        target: /opt/flink/conf/log4j-console.properties

    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - HADOOP_CLASSPATH=/hadoop/etc/hadoop:/hadoop/share/hadoop/common/lib/*:/hadoop/share/hadoop/common/*:/hadoop/share/hadoop/hdfs:/hadoop/share/hadoop/hdfs/lib/*:/hadoop/share/hadoop/hdfs/*:/hadoop/share/hadoop/mapreduce/*:/hadoop/share/hadoop/yarn:/hadoop/share/hadoop/yarn/lib/*:/hadoop/share/hadoop/yarn/*:/hadoop/bin/hadoop
      - KAFKA_BOOTSTRAP=kafka1:9092
      - HADOOP_HOME=/hadoop
    hostname: jobmanager
    deploy:

      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==jm"


  taskmanager1:
    image: jawadtahir/flink-ops-playground:latest
#    image: flink:1.15.2-scala_2.12-java11
    networks:
      - infra
    entrypoint: "taskmanager.sh start-foreground"
    volumes:
      - /home/ubuntu/hadoop/hadoop-3.3.6:/hadoop
      - /usr/lib/jvm/java-11-openjdk-amd64:/usr/lib/jvm/java-11-openjdk-amd64

    configs:
      - source: flink_conf
        target: /opt/flink/conf/flink-conf.yaml

      - source: masters_conf
        target: /opt/flink/conf/masters

      - source: workers_conf
        target: /opt/flink/conf/workers

      - source: flink_console_log
        target: /opt/flink/conf/log4j-console.properties
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - HADOOP_CLASSPATH=/hadoop/etc/hadoop:/hadoop/share/hadoop/common/lib/*:/hadoop/share/hadoop/common/*:/hadoop/share/hadoop/hdfs:/hadoop/share/hadoop/hdfs/lib/*:/hadoop/share/hadoop/hdfs/*:/hadoop/share/hadoop/mapreduce/*:/hadoop/share/hadoop/yarn:/hadoop/share/hadoop/yarn/lib/*:/hadoop/share/hadoop/yarn/*:/hadoop/bin/hadoop
      - KAFKA_BOOTSTRAP=kafka1:9092
      - HADOOP_HOME=/hadoop
    hostname: taskmanager1
    deploy:

      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==tm1"

#  taskmanager1a:
#    image: jawadtahir/flink-ops-playground
#    #    image: flink:1.15.2-scala_2.12-java11
#    networks:
#      - infra
#    entrypoint: "taskmanager.sh start-foreground"
#    volumes:
#      - /home/ubuntu/hadoop/hadoop-3.3.6:/hadoop
#      - /usr/lib/jvm/java-11-openjdk-amd64:/usr/lib/jvm/java-11-openjdk-amd64
#
#    configs:
#      - source: flink_conf
#        target: /opt/flink/conf/flink-conf.yaml
#
#      - source: masters_conf
#        target: /opt/flink/conf/masters
#
#      - source: workers_conf
#        target: /opt/flink/conf/workers
#
#      - source: flink_console_log
#        target: /opt/flink/conf/log4j-console.properties
#    environment:
#      - JOB_MANAGER_RPC_ADDRESS=jobmanager
#      - HADOOP_CLASSPATH=/hadoop/etc/hadoop:/hadoop/share/hadoop/common/lib/*:/hadoop/share/hadoop/common/*:/hadoop/share/hadoop/hdfs:/hadoop/share/hadoop/hdfs/lib/*:/hadoop/share/hadoop/hdfs/*:/hadoop/share/hadoop/mapreduce/*:/hadoop/share/hadoop/yarn:/hadoop/share/hadoop/yarn/lib/*:/hadoop/share/hadoop/yarn/*:/hadoop/bin/hadoop
#      - KAFKA_BOOTSTRAP=kafka1:9092
#      - HADOOP_HOME=/hadoop
#    hostname: taskmanager1a
#    deploy:
#
#      replicas: 1
#      placement:
#        constraints:
#          - "node.labels.vmname==tm1"

  pumba_tm1:
    image: jawadtahir/pumbasrvr
    hostname: pumba_tm1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      infra:
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==tm1"


  taskmanager2:
    image: jawadtahir/flink-ops-playground:latest
#    image: flink:1.15.2-scala_2.12-java11
    networks:
      - infra
    entrypoint: "taskmanager.sh start-foreground"
    volumes:
      - /home/ubuntu/hadoop/hadoop-3.3.6:/hadoop
      - /usr/lib/jvm/java-11-openjdk-amd64:/usr/lib/jvm/java-11-openjdk-amd64

    configs:
      - source: flink_conf
        target: /opt/flink/conf/flink-conf.yaml

      - source: masters_conf
        target: /opt/flink/conf/masters

      - source: workers_conf
        target: /opt/flink/conf/workers

      - source: flink_console_log
        target: /opt/flink/conf/log4j-console.properties
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - HADOOP_CLASSPATH=/hadoop/etc/hadoop:/hadoop/share/hadoop/common/lib/*:/hadoop/share/hadoop/common/*:/hadoop/share/hadoop/hdfs:/hadoop/share/hadoop/hdfs/lib/*:/hadoop/share/hadoop/hdfs/*:/hadoop/share/hadoop/mapreduce/*:/hadoop/share/hadoop/yarn:/hadoop/share/hadoop/yarn/lib/*:/hadoop/share/hadoop/yarn/*:/hadoop/bin/hadoop
      - KAFKA_BOOTSTRAP=kafka1:9092
    hostname: taskmanager2
    deploy:

      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==tm2"


#  taskmanager2a:
#    image: jawadtahir/flink-ops-playground
#    #    image: flink:1.15.2-scala_2.12-java11
#    networks:
#      - infra
#    entrypoint: "taskmanager.sh start-foreground"
#    volumes:
#      - /home/ubuntu/hadoop/hadoop-3.3.6:/hadoop
#      - /usr/lib/jvm/java-11-openjdk-amd64:/usr/lib/jvm/java-11-openjdk-amd64
#
#    configs:
#      - source: flink_conf
#        target: /opt/flink/conf/flink-conf.yaml
#
#      - source: masters_conf
#        target: /opt/flink/conf/masters
#
#      - source: workers_conf
#        target: /opt/flink/conf/workers
#
#      - source: flink_console_log
#        target: /opt/flink/conf/log4j-console.properties
#    environment:
#      - JOB_MANAGER_RPC_ADDRESS=jobmanager
#      - HADOOP_CLASSPATH=/hadoop/etc/hadoop:/hadoop/share/hadoop/common/lib/*:/hadoop/share/hadoop/common/*:/hadoop/share/hadoop/hdfs:/hadoop/share/hadoop/hdfs/lib/*:/hadoop/share/hadoop/hdfs/*:/hadoop/share/hadoop/mapreduce/*:/hadoop/share/hadoop/yarn:/hadoop/share/hadoop/yarn/lib/*:/hadoop/share/hadoop/yarn/*:/hadoop/bin/hadoop
#      - KAFKA_BOOTSTRAP=kafka1:9092
#    hostname: taskmanager2a
#    deploy:
#
#      replicas: 1
#      placement:
#        constraints:
#          - "node.labels.vmname==tm2"
#
  pumba_tm2:
    image: jawadtahir/pumbasrvr
    hostname: pumba_tm2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      infra:
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==tm2"


  taskmanager3:
    image: jawadtahir/flink-ops-playground:latest
#    image: flink:1.15.2-scala_2.12-java11
    networks:
      - infra
    entrypoint: "taskmanager.sh start-foreground"
    volumes:
      - /home/ubuntu/hadoop/hadoop-3.3.6:/hadoop
      - /usr/lib/jvm/java-11-openjdk-amd64:/usr/lib/jvm/java-11-openjdk-amd64

    configs:
      - source: flink_conf
        target: /opt/flink/conf/flink-conf.yaml

      - source: masters_conf
        target: /opt/flink/conf/masters

      - source: workers_conf
        target: /opt/flink/conf/workers

      - source: flink_console_log
        target: /opt/flink/conf/log4j-console.properties
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - HADOOP_CLASSPATH=/hadoop/etc/hadoop:/hadoop/share/hadoop/common/lib/*:/hadoop/share/hadoop/common/*:/hadoop/share/hadoop/hdfs:/hadoop/share/hadoop/hdfs/lib/*:/hadoop/share/hadoop/hdfs/*:/hadoop/share/hadoop/mapreduce/*:/hadoop/share/hadoop/yarn:/hadoop/share/hadoop/yarn/lib/*:/hadoop/share/hadoop/yarn/*:/hadoop/bin/hadoop
      - KAFKA_BOOTSTRAP=kafka1:9092
    hostname: taskmanager3
    deploy:

      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==tm3"


#  taskmanager3a:
#    image: jawadtahir/flink-ops-playground
#    #    image: flink:1.15.2-scala_2.12-java11
#    networks:
#      - infra
#    entrypoint: "taskmanager.sh start-foreground"
#    volumes:
#      - /home/ubuntu/hadoop/hadoop-3.3.6:/hadoop
#      - /usr/lib/jvm/java-11-openjdk-amd64:/usr/lib/jvm/java-11-openjdk-amd64
#
#    configs:
#      - source: flink_conf
#        target: /opt/flink/conf/flink-conf.yaml
#
#      - source: masters_conf
#        target: /opt/flink/conf/masters
#
#      - source: workers_conf
#        target: /opt/flink/conf/workers
#
#      - source: flink_console_log
#        target: /opt/flink/conf/log4j-console.properties
#    environment:
#      - JOB_MANAGER_RPC_ADDRESS=jobmanager
#      - HADOOP_CLASSPATH=/hadoop/etc/hadoop:/hadoop/share/hadoop/common/lib/*:/hadoop/share/hadoop/common/*:/hadoop/share/hadoop/hdfs:/hadoop/share/hadoop/hdfs/lib/*:/hadoop/share/hadoop/hdfs/*:/hadoop/share/hadoop/mapreduce/*:/hadoop/share/hadoop/yarn:/hadoop/share/hadoop/yarn/lib/*:/hadoop/share/hadoop/yarn/*:/hadoop/bin/hadoop
#      - KAFKA_BOOTSTRAP=kafka1:9092
#    hostname: taskmanager3a
#    deploy:
#
#      replicas: 1
#      placement:
#        constraints:
#          - "node.labels.vmname==tm3"
#
#
  pumba_tm3:
    image: jawadtahir/pumbasrvr
    hostname: pumba_tm3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      infra:
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==tm3"

  flink_client:
    image: jawadtahir/flink-ops-playground:latest
    networks:
      - infra
    depends_on:
      - taskmanager3
    configs:
      - source: flink_conf
        target: /opt/flink/conf/flink-conf.yaml

      - source: masters_conf
        target: /opt/flink/conf/masters

      - source: workers_conf
        target: /opt/flink/conf/workers

    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - KAFKA_BOOTSTRAP=kafka1:9092
    hostname: flink_client
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.labels.vmname==jm"


configs:
  flink_conf:
    file: ./conf/flink-conf.yaml

  masters_conf:
    file: ./conf/masters

  workers_conf:
    file: ./conf/workers

  flink_console_log:
    file: ./conf/log4j-console.properties

networks:
  infra:
    name: infra
    external: true