version: '3.9'


services:
  redis:
    image: redis
    hostname: redis
    networks:
      infra:
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==utils2"


  nimbus:
    image: jawadtahir/storm
    hostname: nimbus
#    volumes:
#      - ./storm-conf/worker.xml:/apache-storm-2.4.0/log4j2/worker.xml
    entrypoint: storm nimbus
    depends_on:
      - zookeeper
    configs:
      - source: storm_config
        target: /conf/storm.yaml
    networks:
      infra:
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==nimbus"

  pumba_nimbus:
    image: jawadtahir/pumbasrvr
    hostname: pumba_nimbus
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      infra:
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==nimbus"


  supervisor1:
    image: jawadtahir/storm
    hostname: supervisor1
    depends_on:
      - nimbus
#    volumes:
#      - ./storm-conf/worker.xml:/apache-storm-2.4.0/log4j2/worker.xml
    entrypoint: storm supervisor
    configs:
      - source: storm_config
        target: /conf/storm.yaml
    networks:
      infra:
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==supervisor1"

  pumba_supervisor1:
    image: jawadtahir/pumbasrvr
    hostname: pumba_supervisor1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      infra:
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==supervisor1"

  supervisor2:
    image: jawadtahir/storm
    hostname: supervisor2
    depends_on:
      - nimbus
    #    volumes:
    #      - ./storm-conf/worker.xml:/apache-storm-2.4.0/log4j2/worker.xml
    entrypoint: storm supervisor
    configs:
      - source: storm_config
        target: /conf/storm.yaml
    networks:
      infra:
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==supervisor2"

  pumba_supervisor2:
    image: jawadtahir/pumbasrvr
    hostname: pumba_supervisor2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      infra:
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==supervisor2"

  supervisor3:
    image: jawadtahir/storm
    hostname: supervisor3
    depends_on:
      - nimbus
    #    volumes:
    #      - ./storm-conf/worker.xml:/apache-storm-2.4.0/log4j2/worker.xml
    entrypoint: storm supervisor
    configs:
      - source: storm_config
        target: /conf/storm.yaml
    networks:
      infra:
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==supervisor3"

  pumba_supervisor3:
    image: jawadtahir/pumbasrvr
    hostname: pumba_supervisor3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      infra:
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==supervisor3"


  stormUI:
    image: jawadtahir/storm
#    hostname: stormUI
    depends_on:
      - supervisor1
    entrypoint: storm ui
#    volumes:
#      - ./storm-conf/storm.yaml:/conf/storm.yaml
    configs:
      - source: storm_config
        target: /conf/storm.yaml
        mode: 0777
    networks:
      infra:
    ports:
      - target: 8080
        published: 58080
        mode: host
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==utils2"

  storm_jar:
    image: jawadtahir/storm
    depends_on:
      - nimbus
    environment:
      - NIMBUS_SEED=nimbus
      - KAFKA_SEED=kafka1:9092
      - KAFKA_INPUT_TOPIC=click
      - KAFKA_UPDATE_TOPIC=update
      - KAFKA_OUTPUT_TPOIC=output
    networks:
      infra:
    deploy:
      placement:
        constraints:
          - "node.labels.vmname==utils2"
      restart_policy:
        condition: on-failure

  prompgw:
    image: prom/pushgateway
    depends_on:
      - nimbus
    hostname: prompgw
    networks:
      infra:
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==utils2"

#  stormTop:
#    image: jawadtahir/storm
#    depends_on:
#      - stormUI
#    command: "storm jar /apache-storm-2.4.0/bin/ClickCountJob.jar de.tum.in.msrg.storm.StormTopology kafka:9092 nimbus"
#    restart: on-failure
#    networks:
#      storm:
#

configs:
  storm_config:
    file: ./storm-conf/storm.yaml

networks:
  infra:
    name: infra
    external: true
