version: '3.9'


services:


  zookeeper:
    image: zookeeper:3.5.9
    hostname: zookeeper
    networks:
      test:


  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    networks:
      test:
    depends_on:
      - zookeeper
    hostname: kafka

    ports:
      - target: 9094
        published: 9094
        mode: host
      - target: 9092
        published: 9092
        mode: host

    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://localhost:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "click:1:1, update:1:1, output:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LOG_RETENTION_BYTES: 3758096384 #3.5 GB
#      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 60000 # 1 minutes





networks:
  test:

