version: '3.9'

services:
  datagen:
    image: jawadtahir/kafka-data-gen
    build:
      context: ../docker/kafka-data-gen
    hostname: datagen
    networks:
      infra:
    environment:
      DELAY_COUNT:
      KAFKA_BOOTSTRAP: kafka1:9092

    configs:
      - source: log4j2_datagen
        target: /jar/log4j2.xml

    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==utils"


  latcal:
    image: jawadtahir/latcal
    build:
      context: ../docker/latcal
    hostname: latcal
    networks:
      infra:
    environment:
      KAFKA_BOOTSTRAP: kafka1:9092
    configs:
      - source: log4j2_latcal
        target: /jar/log4j2.xml

    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==utils"


configs:
  log4j2_latcal:
    file: ./conf/log4j2-latcal.xml

  log4j2_datagen:
    file: ./conf/log4j2-datagen.xml






networks:
  infra:
    name: infra
    external: true