################################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

version: "3.9"

services:

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    networks:
      - infra
    hostname: zookeeper
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmtype==man"

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    networks:
      - infra
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "input:3:1, output:3:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_RETENTION_BYTES: 3758096384 #3.5 GB
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 60000 # 1 minutes

#      KAFKA_LOG_RETENTION_MINUTES: 15
#    ports:
#      - "9092:9092"
    volumes:
      - $DATA_DIR/kafka-logs:/kafka
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmtype==jm"



  prometheus:
    image: prom/prometheus
    networks:
      - infra
    entrypoint: /bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --storage.tsdb.retention.size=10GB --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - $DATA_DIR/prometheus:/prometheus
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmtype==man"

  grafana:
    image: grafana/grafana
    networks:
      - infra
    depends_on:
      - prometheus
    ports:
      - target: 3000
        published: 43000
        mode: host
    volumes:
      - $DATA_DIR/grafana:/var/lib/grafana
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmtype==man"



  jobmanager:
    image: apache/flink:1.14.4-scala_2.12-java8
    networks:
      - infra
    command: "jobmanager.sh start-foreground"
    depends_on:
      - prometheus
    ports:
      - target: 8081
        published: 48081
        mode: host
    volumes:
      - ./lib:/opt/flink/usrlib
      - ./conf:/opt/flink/conf
      - ./lib/oshi-core-3.4.0.jar:/opt/flink/lib/oshi-core-3.4.0.jar
      - ./lib/jna-4.2.2.jar:/opt/flink/lib/jna-4.2.2.jar
      - ./lib/jna-platform-4.2.2.jar:/opt/flink/lib/jna-platform-4.2.2.jar
      - ./lib/flink-shaded-hadoop-2-uber-2.8.3-9.0.jar:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-9.0.jar
      - $CHECKPOINT_DIR:/tmp/flink-checkpoints-directory
      - $SAVEPOINT_DIR:/tmp/flink-savepoints-directory
      - /home/ubuntu/hadoop-3.3.2:/hadoop
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - HADOOP_CLASSPATH=/hadoop/bin/hadoop classpath
    hostname: jobmanager
    deploy:

      replicas: 1
      placement:
        constraints:
          - "node.labels.vmtype==jm"

  pumbasrvr_jm:
    image: jawadtahir/pumbasrvr
    networks:
      - infra
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GRAFANA_URL=http://grafana:3000/api/annotations
      - GRAFANA_API_KEY=eyJrIjoiMkkyZnpwWjBSUFVJUzZlNWM2VmwzdXdFTHhyQ1ZMQWgiLCJuIjoicHVtYmFzcnZyIiwiaWQiOjF9
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmtype==jm"


  taskmanager:
    image: apache/flink:1.14.4-scala_2.12-java8
    networks:
      - infra
    depends_on:
      - jobmanager
    command: "taskmanager.sh start-foreground"
    volumes:
      - ./lib:/opt/flink/usrlib
      - ./conf:/opt/flink/conf
      - ./lib/oshi-core-3.4.0.jar:/opt/flink/lib/oshi-core-3.4.0.jar
      - ./lib/jna-4.2.2.jar:/opt/flink/lib/jna-4.2.2.jar
      - ./lib/jna-platform-4.2.2.jar:/opt/flink/lib/jna-platform-4.2.2.jar
      - $CHECKPOINT_DIR:/tmp/flink-checkpoints-directory
      - $SAVEPOINT_DIR:/tmp/flink-savepoints-directory
      - /home/ubuntu/hadoop-3.3.2:/hadoop
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - HADOOP_CLASSPATH=/hadoop/bin/hadoop classpath
    hostname: taskmanager
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==tm1"

  pumbasrvr_tm1:
    image: jawadtahir/pumbasrvr
    networks:
      - infra
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GRAFANA_URL=http://grafana:3000/api/annotations
      - GRAFANA_API_KEY=eyJrIjoiMkkyZnpwWjBSUFVJUzZlNWM2VmwzdXdFTHhyQ1ZMQWgiLCJuIjoicHVtYmFzcnZyIiwiaWQiOjF9
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==tm1"


  taskmanager1:
    image: apache/flink:1.14.4-scala_2.12-java8
    networks:
      - infra
    depends_on:
      - jobmanager
    command: "taskmanager.sh start-foreground"
    volumes:
      - ./lib:/opt/flink/usrlib
      - ./conf:/opt/flink/conf
      - ./lib/oshi-core-3.4.0.jar:/opt/flink/lib/oshi-core-3.4.0.jar
      - ./lib/jna-4.2.2.jar:/opt/flink/lib/jna-4.2.2.jar
      - ./lib/jna-platform-4.2.2.jar:/opt/flink/lib/jna-platform-4.2.2.jar
      - $CHECKPOINT_DIR:/tmp/flink-checkpoints-directory
      - $SAVEPOINT_DIR:/tmp/flink-savepoints-directory
      - /home/ubuntu/hadoop-3.3.2:/hadoop
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - HADOOP_CLASSPATH='/hadoop/bin/hadoop classpath'
    hostname: taskmanager1
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==tm2"

  pumbasrvr_tm2:
    image: jawadtahir/pumbasrvr
    networks:
      - infra
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GRAFANA_URL=http://grafana:3000/api/annotations
      - GRAFANA_API_KEY=eyJrIjoiMkkyZnpwWjBSUFVJUzZlNWM2VmwzdXdFTHhyQ1ZMQWgiLCJuIjoicHVtYmFzcnZyIiwiaWQiOjF9
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==tm2"

  taskmanager2:
    image: apache/flink:1.14.4-scala_2.12-java8
    networks:
      - infra
    depends_on:
      - jobmanager
    command: "taskmanager.sh start-foreground"
    volumes:
      - ./lib:/opt/flink/usrlib
      - ./conf:/opt/flink/conf
      - ./lib/oshi-core-3.4.0.jar:/opt/flink/lib/oshi-core-3.4.0.jar
      - ./lib/jna-4.2.2.jar:/opt/flink/lib/jna-4.2.2.jar
      - ./lib/jna-platform-4.2.2.jar:/opt/flink/lib/jna-platform-4.2.2.jar
      - $CHECKPOINT_DIR:/tmp/flink-checkpoints-directory
      - $SAVEPOINT_DIR:/tmp/flink-savepoints-directory
      - /home/ubuntu/hadoop-3.3.2:/hadoop
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - HADOOP_CLASSPATH="/hadoop/bin/hadoop classpath"
    hostname: taskmanager2
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==tm3"

  pumbasrvr_tm3:
    image: jawadtahir/pumbasrvr
    networks:
      - infra
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GRAFANA_URL=http://grafana:3000/api/annotations
      - GRAFANA_API_KEY=eyJrIjoiMkkyZnpwWjBSUFVJUzZlNWM2VmwzdXdFTHhyQ1ZMQWgiLCJuIjoicHVtYmFzcnZyIiwiaWQiOjF9
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==tm3"

networks:
  infra: