version: '3.9'

services:
  kstreams1:
    image: jawadtahir/kafka-streams-topology:latest
    hostname: kstreams1
    environment:
      APPID: kafka-streams-count
      KAFKA_BOOTSTRAP: "kafka1:9092,kafka2:9092,kafka3:9092"
      PROCESSING_GUARANTEE:
      STANDBY: 0
      NUM_STREAMS:
    configs:
      - source: kstreams_log_config
        target: /kafka-topology/log4j2.xml
    networks:
      infra:

    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==kstreams1"


  pumba_ks1:
    image: jawadtahir/pumbasrvr:latest
    hostname: pumba_ks1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      infra:
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.vmname==kstreams1"


configs:
  kstreams_log_config:
    file: ./conf/log4j2-kstreams.xml


networks:
  infra:
    name: infra
    external: true
